[package]
name = "galactic_guide"
version = "0.1.0"
edition = "2021"
default-run = "galactic_guide"

[dependencies]
bevy = "0.13.2"
bevy_egui = "0.27.1"
nyx-space = "1.1.2"
smooth-bevy-cameras = "0.11.0"
strum = "0.26.3"
strum_macros = "0.26.4"